version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    # environment: 
    #   POSTGRES_USER: 
    #   POSTGRES_PASSWORD: 
    #   POSTGRES_DB: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - milyoner-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    networks:
      - milyoner-network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - milyoner-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: milyoner_backend
    container_name: m_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    # environment:
    #   DB_URL: 
    #   DB_USERNAME: 
    #   DB_PASSWORD: 
    #   REDIS_HOST: redis
    #   REDIS_PORT: 6379
    #   REDIS_PASSWORD: ""
    #   JWT_SECRET: 
    #   JWT_EXPIRATION: 
    depends_on:
      - postgres
      - redis
    networks:
      - milyoner-network

volumes:
  postgres_data:
  redis_data:

networks:
  milyoner-network:
    name: milyoner-shared-network
    driver: bridge