spring:
  application:
    name: milyoner
  datasource:
    url: jdbc:postgresql://localhost:5432/milyoner?currentSchema=game
    username: postgres
    password: postgres
    #  jpa:
    #    hibernate:
    #      ddl-auto: update # todo : will be change
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: game
    create-schemas: true

jwt:
  secret: 3e217b5210de6eedfca87ea615b8c5fbb17cecb0f5bec50555176d191060f66f
  expiration: 3600000