spring:
  application:
    name: milyoner
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    #  jpa:
    #    hibernate:
    #      ddl-auto: update # todo : will be change
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: game
    create-schemas: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

rate-limit:
  login:
    limit: 5
    window-minutes: 1
  register:
    limit: 3
    window-hours: 1
